name: Deploy to server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Build API
        uses: appleboy/ssh-action@master
        env:
          CONTRACT_OWNER_ADDRESS: ${{ secrets.CONTRACT_OWNER_ADDRESS }}
          CONTRACT_OWNER_PK: ${{ secrets.CONTRACT_OWNER_PK }}
          COLLECTION_CONTRACT_ADDRESS: ${{ secrets.COLLECTION_CONTRACT_ADDRESS }}
          PAYMENT_CONTRACT_ADDRESS: ${{ secrets.PAYMENT_CONTRACT_ADDRESS }}
          WITHDRAW_CONTRACT_ADDRESS: ${{ secrets.WITHDRAW_CONTRACT_ADDRESS }}
          MONGODB_URL: ${{ secrets.MONGODB_URL }}
          ETH_NETWORK: ${{ secrets.ETH_NETWORK }}
          INFURA_PROJECT_ID: ${{ secrets.INFURA_PROJECT_ID }}
          NODE_ENV: production
          NODE_APP_INSTANCE: 1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          envs: CONTRACT_OWNER_ADDRESS,CONTRACT_OWNER_PK,COLLECTION_CONTRACT_ADDRESS,PAYMENT_CONTRACT_ADDRESS,WITHDRAW_CONTRACT_ADDRESS,MONGODB_URL,ETH_NETWORK,INFURA_PROJECT_ID,NODE_ENV,NODE_APP_INSTANCE
          script: |
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            nvm use 16
            cd ~/backdoor-casino
            git pull origin main
            cd packages/api
            yarn install --frozen-lockfile
            yarn compile
            pm2 start
      - name: Build frontend
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            nvm use 16
            cd ~/backdoor-casino/packages/frontend
            yarn install --frozen-lockfile
            yarn build
      - name: Build admin
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            export NVM_DIR=~/.nvm
            source ~/.nvm/nvm.sh
            nvm use 16
            cd ~/backdoor-casino/packages/admin
            yarn install --frozen-lockfile
            yarn build
